### PR TITLE
Config to save requested claims

### LINKED ISSUE #7: Allow setting more claims from the ID token to the Plug.Conn.t()
Right now there exists a callback called with the tokens after redirect (https://hexdocs.pm/plugoid/Plugoid.RedirectURI.html#module-options).

The initial idea was to use it with the `oauth2_token_manager` library, but this one is not production ready (and won't as long as there's no good solution for clustered deployments).

Right now only the `"sub"` and `"acr"` claims are set in Plugoid's session. As requested by a user on a forum, it would be nice if more claims could be set in the session. 2 possible ways:
- having the callback return a `Plug.Conn.t()` so that the user can set anything he wants in the session
- add an option to choose which additional claims to add to Plugoid's authentication session

### PR DESCRIPTION
**Pull request by brianmay**
Fixes #7

### CODE REVIEW

**Comment by brianmay** [comment]
Note this will break existing sessions. Not sure how much that matters...

**Comment by brianmay** [comment]
dialyzer passes. Which is somewhat amazing.

I can't test act stuff, but hopefully I didn't break it (except for existing sessions). Everything else looks good to me.

**Comment by tanguilp** [comment]
The problem with this approach is that cookies have size limit, and authentication cookies can hold authentication info of several sessions. This could be a problem when using the COOKIE backend (data stored in the cookie and not in a backend).

This would be nice if we could configure which claims are saved, and which ones are not.

**Comment by brianmay** [comment]
This PR does allow specifying which claims you do/don't want to keep. Not sure I would ever need any more then this?

But yes, if it supported a function as well as a list, I guess it could be more generic.

**Comment by tanguilp** [comment]
There's also the alternative which consist in giving the opportunity to the user to to whatever he wants with the claims (and tokens) and the `Plug.Conn.t`, for example saving them in its own session. See #7

**Comment by brianmay** [comment]
Feel free to take this PR and modify more in line of what you want.

**Comment by tanguilp** [comment]
I've taken the second approach: in the `conn_callback` branch the token callback takes the conn as a parameter and returns it. It should be sufficient to set whatever you want in the session.

https://github.com/tanguilp/plugoid/tree/conn_callback

Feel free to test it and give me feedback.

**Comment by brianmay** [comment]
Thanks. Will test ASAP.

I imagine this means the callback can put data in the default phoenix session, which would solve one of the problems we were predicting with the live view not having access to the required session details.

Wondering if the special case code for subject is still required though. We might want to include it in the default session also, so that live views have access. Which would mean we get two copies.

**Comment by brianmay** [comment]
I am going to put this URL here so I don't have to keep finding it. Seems the appropriate place anyway:

https://github.com/tanguilp/plugoid/compare/conn_callback

**Comment by brianmay** [comment]
So far, your branch seems to work fine.

**Comment by brianmay** [comment]
Odd. Seems to have stopped working. Thinking this is probably my fault. But out of time to look now, will look later.

**Comment by brianmay** [comment]
If you want to merge your branch, we can then close this PR.

**Comment by brianmay** [comment]
Will close and summarise in #7.

**Pull request closed without merging**
